### ISSUE TITLE
"Console" is opened everytime I run pandown

### ISSUE THREAD

**Issue by openmedi** [phyllisstein/Pandown#28]
Whenever I run pandown, a little "console" (it's not called that, but I don't know the name…) is displayed, even when no output in that window is generated. I would like pandown to not open up this console pane, if it has nothing to show. Is that possible?

**Comment by phyllisstein** [comment]
Hey there! Pandown respects Sublime's global `show_panel_on_build` setting, so you can add this to your `Preferences.sublime-settings` file:

```json
"show_panel_on_build": false
```

You could also add that to your syntax-specific settings if you want the panel to show for everything _but_ Markdown.

**Comment by openmedi** [comment]
Thanks, that worked. In order for me to see the panel manually, I also added the following shortcut to my key bindings file:

```
{ "keys": ["ctrl+alt+b"], "command": "show_panel", "args": {"panel": "output.exec"} }
```

**Comment by phyllisstein** [comment]
Great! Sublime has a built-in shortcut, `Super+Alt+B`, if that's useful; you can also toggle it from the menu under Tools→Build Results→Show Build Results. Good luck!

**Comment by openmedi** [comment]
(NB: ```super+alt+b``` is the standard shortcut for making something bold by people who have Markdown Editing installed - which is, I assume, probably 99% of pandown users.)

**Comment by phyllisstein** [comment]
Aha! Thank you for that :-). I do not myself use Markdown Editing, so I wasn't aware. Good to have that in my back pocket.
